### ISSUE TITLE
LUA Scripting

### ISSUE THREAD

**Issue by Jacob-Mango** [TheCherno/Sparky#102]
Could I possibly be the person working on implementing LUA scripting?

**Comment by KevinW1998** [comment]
There is already an issue open concerning LUA scripting. See #23. If you really want to add lua scripting then I highly recommend luajit.

**Comment by Jacob-Mango** [comment]
@KevinW1998 Oh, did not see that. Will ask to be assigned in there and close this one.

I have already started so it is a bit late for me to change on which library to use.
