### ISSUE TITLE
Change GLFW window resize callback

### ISSUE THREAD

**Issue by CaioIcy** [TheCherno/Sparky#11]
Hello,

inside [Window::init()](https://github.com/TheCherno/Sparky/blob/master/Sparky-core/src/graphics/window.cpp#L46) you call **glfwSetWindowSizeCallback** to use **glViewport** in the callback.

In [GLFW's documentation](http://www.glfw.org/docs/latest/window.html#window_size) they say why you shouldn't use that function:

> "Do not pass the window size to glViewport or other pixel-based OpenGL calls. The window size is in screen coordinates, not pixels. Use the framebuffer size, which is in pixels, for pixel-based calls."

So you should change **glfwSetWindowSizeCallback** to **glfwSetFramebufferSizeCallback**, which will be correct.

**Comment by CaioIcy** [comment]
I just saw that this has already been addressed, but [by a pull request](https://github.com/TheCherno/Sparky/pull/2). I'll leave this issue here, since it explains why the change should be made.

**Comment by TheCherno** [comment]
I'll change it to this in the upcoming maintenance episode (Ep. 20).
