### ISSUE TITLE
In Test3d can't move camera neither walk on the scene

### ISSUE THREAD

**Issue by rpsfonseca** [TheCherno/Sparky#122]
Wanted to check if I had everything right after pulling the source code from github, uncommented the line 32 of Sandbox.cpp to test the 3D scene, build was good, no problems, and, although it showed the scene, the camera wouldn't move neither could I walk on the scene, as I saw doing on the "How to contribute to Sparky" video.

I think it might be a bug of some sort, since I didn't see any other steps needed for it to run, on the videos or here on github.

**Comment by jannisj1** [comment]
Just press c m8

**Comment by rpsfonseca** [comment]
Yeap, I was missing that step!
Thank  you!
