### ISSUE TITLE
Sparky, Also suitable for 3d games?

### ISSUE THREAD

**Issue by adunStudio** [TheCherno/Sparky#133]
I need a simple engine to compile the 3d game

with analyzing the source.

Is this engine suitable for 3d game production?

or is it only optimized for 2d?

**Comment by TheCherno** [comment]
Yes, Sparky supports 3D. Please note this is currently not an actively developed engine, so use at your own risk. At the very least Sparky provides you with a fairly stable 3D forward OpenGL/Direct3D 11 renderer + material system, but be prepared to do some debugging/code modifying to configure it based on your needs.

Additionally if you need help you can join my Discord server at https://thecherno.com/discord
