### ISSUE TITLE
[OPTIONAL] Include guards

### ISSUE THREAD

**Issue by WhoseTheNerd** [TheCherno/Sparky#136]
It fixes errors like circular reference between headers and C1014. Makes executable file smaller.

Here's some links:
https://en.wikipedia.org/wiki/Include_guard
http://www.cplusplus.com/forum/general/71787/

**Comment by riesinger** [comment]
Sparky uses include guards (building sth. like Sparky would not be possible without it), can you elaborate on what you mean exactly?

**Comment by WhoseTheNerd** [comment]
I don't see include guards in SOURCE CODE of header file. Include guard is like: is this defined? if yes then don't include that, if no then include that.

**Comment by KevinW1998** [comment]
It does use include guard. `#pragma once` basically does it, which you can find in every header.

**Comment by WhoseTheNerd** [comment]
Ok, i know that, but i meant '#ifndef SOUND_H \n #define SOUND_H \n "CODE" \n #endif'. My link to wikipedia explains this.
