### ISSUE TITLE
ImageLoad free dib data

### ISSUE THREAD

**Issue by holgk** [TheCherno/Sparky#15]
We create a `FIBITMAP *dib` pointer and check if there is data but we do not free the data through a delete dib. I don't know much about FreeImage but i don't thing our `BYTE* result` is pointing to the same data.

**Comment by TheCherno** [comment]
This will be handled in the upcoming maintenance episode (Ep. 20). I left a comment in Texture::load to remind myself. :)

**Comment by TheCherno** [comment]
Fixed in Ep. 20.
