### ISSUE TITLE
m_Buffers in vertexarray never filled 

### ISSUE THREAD

**Issue by Maxchii** [TheCherno/Sparky#17]
Files: `vertexarray.h` and `vertexarray.cpp`

Seems like `std::vector<Buffer*> m_Buffers;` is defined, however there is no logic that adds  buffers to the vector. Therefore making the loop in  `VertexArray::~VertexArray()`  and  `std::vector<Buffer*>`vector unnecessary.

**Comment by TheCherno** [comment]
Fixed in Ep. 20! Thanks. :)

**Comment by Maxchii** [comment]
No problem!
