### ISSUE TITLE
OpenAL

### ISSUE THREAD

**Issue by Ilohama** [TheCherno/Sparky#25]
Hey, I had a probleme with sparky..... At start, I've tried to take your OpenAL.dll from your github (the good one) and just run sparky (audio). I had an error (code : 0xc00007b). Then I get to the OpenAL website and I installed the SDK (like you). It fixed the problem but i'm worried about people that use Sparky... I think we have to test Sparky on multiple desktops without this OpenAL SDK installed to confirm that issue.

More over, I insist that i've the same code as you, your Sparky Engine like tuto's one.
To be sure, I pulled the code from commit Ep.23, compiled it and run it.... same error like before.

Have a nice dayy~~

**Comment by JeppeSRC** [comment]
That error occurs when you try to load a 32 bit dll in a 64 bit executable(or wise versa). So make sure the executable and dll are both 32 or 64 bit :+1:
