### ISSUE TITLE
Texture glitch.

### ISSUE THREAD

**Issue by Worly** [TheCherno/Sparky#30]
Adding sprite and label in same layer causes sprite to glitch. I didn't saw this bug on your videos, but I think it's not problem only for me. I tried on your code too.

![glitch](https://cloud.githubusercontent.com/assets/12067631/7274769/fb7b3c64-e8ff-11e4-8dd6-0c753b5d12c3.png)

**Comment by tannous3** [comment]
Hello, did you fix that issue ? (I mean making it work without the different layer), because for me it's the same (unless I do a different layer)

**Comment by Worly** [comment]
Sorry, can't remember, it's been two years :/

**Comment by tannous3** [comment]
It's alright, just fixed it XD
