### ISSUE TITLE
Linux user!

### ISSUE THREAD

**Issue by ghost** [TheCherno/Sparky#37]
Hello!
I'm a Elementary Os freya(Ubuntu 14.04) user and I'd like to contribute to sparky but I cant since I dont have the possibility to load the engine into CodeBlocks(and VS does not work on Linux).My point is that many users may have different OSs than Windows and we cant use sparky.This needs to be fixed.
So I think the best option would be to make sparky work with CodeBlocks because that ide works cross platform.

**Comment by TheCherno** [comment]
Why don't you have a go at creating a Linux build of Sparky?

I don't happen to have a computer with Linux on it right now, but you do! :)

**Comment by ghost** [comment]
Ok,I'll do my best!

**Comment by JeppeSRC** [comment]
Murii you could give visual studio code a try, it runs on windows, linux and mac. I don't know if it can open the same visual studio projects, but i guess it can(would be pretty stupid buy Microsoft to do otherwise) :)

**Comment by ghost** [comment]
Last time when I used it(when it was on update 2) it could not open VS projects.Visual studio code it's just for Web so far.

**Comment by JeppeSRC** [comment]
Oh, I thought you could write c/c++ in it :)

**Comment by valipopescu** [comment]
Just go ahead and create a CMakeLists.txt file and maintain it yourself :) I'm quite sure Cherno wouldn't mind putting it in the project and using it (it'll help portability with a lot of platforms)

**Comment by TheCherno** [comment]
Exactly. I don't have the time to add Linux support right now, but I would sure love to accept some pull requests.

**Comment by tdgroot** [comment]
@Murii I guess you should be less demanding and contribute to the project instead..

Guess this issue can be closed for now.. 
Please close it and move the conversation to https://github.com/TheCherno/Sparky/issues/112.

**Comment by jannisj1** [comment]
@Desmaster The salt is real

**Comment by S-Marais** [comment]
I wanted to have a better understanding of how OpenGL works and the video series helped me go through that. (Awesome work btw).
As the engine is OpenGL based I started to write it from scratch using cmake with clang on linux.
The main difference so far is my drop of the maths functions in favor of the glm library.
I'm using CLion but it should also work nicely with codelite. I find codeblocks a bit too old.
