### ISSUE TITLE
Render API CreateVertexBuffers()

### ISSUE THREAD

**Issue by LPeter1997** [TheCherno/Sparky#50]
```
inline void CreateVertexArrays(uint size, uint* arrays)
{
    GLCall(glGenVertexArrays(size, arrays));
}

inline void CreateVertexBuffers(uint size, uint* buffers)
{
    GLCall(glGenVertexArrays(size, buffers));
}
```

These are doing exactly the same. Didn't you want to write glGenBuffers on the second one?

**Comment by TheCherno** [comment]
Good catch! Luckily that wasn't used anywhere (although I probably would have discovered it if it had). Fixed in latest commit. Thanks! :)
