### ISSUE TITLE
It gives me en error.

### ISSUE THREAD

**Issue by FinnT730** [TheCherno/Sparky#58]
When I want to show the Debug Menu, its is not showing!
Maybe its just me, or its an bug!

**Comment by Shimmen** [comment]
With some better description we could try to solve it together. Essentially, what error does it give you, etc.?

**Comment by FinnT730** [comment]
No only the FPS an this is my code, http://pastebin.com/P4HfZ0t6

I already try'd to fix the problem by my self, but it didn't work!

**Comment by Shimmen** [comment]
I'm not sure what you mean, and this probably isn't the place to discuss it. I would refer to the Cherno slack channel.

**Comment by FinnT730** [comment]
Okay.
Thanks anyway!
