### ISSUE TITLE
bgfx as rendering api

### ISSUE THREAD

**Issue by catinwarmhands** [TheCherno/Sparky#64]
Have you heard of [bgfx lib](https://github.com/bkaradzic/bgfx) ?
It provides opengl, opengl es, webgl, directx (9, 11, 12) and metal support.
I thinck it would be awesome to use this lib in sparky engine
Check out examples [here](https://bkaradzic.github.io/bgfx/examples.html)

**Comment by TheCherno** [comment]
Looks like it will be a great resource to refer to, however Sparky is going to rock its own renderers, for obvious reasons. Thanks for bringing this to my attention though, should definitely help. :)
