### ISSUE TITLE
FPS Camera mouse recapture after pressing Esc failed

### ISSUE THREAD

**Issue by ghost** [TheCherno/Sparky#67]
To reproduce the bug:
- run the program
- once the scene is loaded, press c to enter FPS camera
- free mouse pointer pressing `Esc`
- click into the window

The result is that nothing happens, it should recapture the mouse, as explained in the previous devlog.

**Comment by Gogsi** [comment]
Mouse recapturing happens with right clicking on the window.
You can change that at line 32 in FPSCamera.cpp from SP_MOUSE_RIGHT to SP_MOUSE_LEFT.

As Cherno will probably read this I might add something which is sort of on the same topic: In FPSCamera:46 you print the mouse X and Y every update which is not really needed.

**Comment by ghost** [comment]
Ok thanks, so that's not an issue.

**Comment by TheCherno** [comment]
@Gogsi Whoops, forgot to remove that. :)
