### ISSUE TITLE
Direct3D not working!

### ISSUE THREAD

**Issue by maxoberberger** [TheCherno/Sparky#68]
Sparky fails to init Direct3D:
"Ausnahme ausgelöst bei 0x0FA11D42 (SPCore.dll) in Sandbox.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x00000000."
(sorry for having vs is german)
This happens in DXContext.cpp. The D3D11CreateDevice method does not create a device, so when the ID3D11Device\* dev pointer is used I get a NullpointerException (or whatever you call this in c++).

**Comment by Uliori** [comment]
I think that you need to install Windows SDK.
For win 10,  the link is : https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by maxoberberger** [comment]
Thanks, that fixed the problem!

**Comment by TheCherno** [comment]
The reason you need the Windows SDK is probably because the Direct3D Debug Layer is enabled. If you disable it, I'm sure you won't need the SDK installed.
