### ISSUE TITLE
Redundant assertion in AllocateDebug() 

### ISSUE THREAD

**Issue by PistonMiner** [TheCherno/Sparky#69]
The assertion in [L33](https://github.com/TheCherno/Sparky/blob/master/Sparky-core/src/sp/system/Allocator.cpp#L33) can be removed due to it already being asserted in Allocate().

**Comment by TheCherno** [comment]
I think my plan was to not return Allocate() from AllocateDebug, but rather use something else. I just didn't get around to it so I'm returning Allocate() from now. That assertion will need to be brought back when this function gets properly implemented, so no need to remove it for now.
