### ISSUE TITLE
"Sandbox.exe has stopped working" Sandbox.exe crashes

### ISSUE THREAD

**Issue by PixelSpew** [TheCherno/Sparky#74]
<img width="854" alt="capture" src="https://cloud.githubusercontent.com/assets/10374421/14221337/eaf60a2c-f85d-11e5-9a0c-95c4febb30a3.PNG">

**Comment by RomanTruhanov** [comment]
yes I find this bug (run compiled program in my notebook)

**Comment by TheCherno** [comment]
I believe this is closed. You need to make sure to copy the Sandbox resources into the same directory as Sandbox.exe if you run it outside of Visual Studio. Sparky should have a better error message though, that's for sure. :)
