### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [TheCherno/Sparky#88]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) in [the destructor for the class "ManagedClass"](https://github.com/TheCherno/Sparky/blob/612f7cae436a8a1918ce4d27a0bf8f4a68028674/SparkyCLI/src/SparkyCLI.h#L40).

**Comment by ghost** [comment]
Creating a pull request for this is easier

**Comment by KevinW1998** [comment]
The CLI version will be rewritten anyway at some point, so there is no need to focus on the CLI version.

**Comment by TheCherno** [comment]
SparkyCLI will indeed be re-written, and this is really stale code.
