### ISSUE TITLE
No keyboard or mouse input in sandbox

### ISSUE THREAD

**Issue by wallertech** [TheCherno/Sparky#96]
Forked sparky, compiled to whatever the default settings are once you clone it, compiled on windows 7 64 bit with the newest version of visual studio, sandbox will run and render everything just won't record my key or mouse input.

**Comment by jannisj1** [comment]
@wallertech try my forked version, should be fixed in there

**Comment by Ilohama** [comment]
What are you trying to do to say inputs won't work?

**Comment by wallertech** [comment]
@jannisj1 alright I will check it out buddy.

@Xeryko Trying to run sandbox, maybe im just an idiot and you have to code the input yourself but in chernos vids he can move around so I assumed it was working in sandbox.

**Comment by jannisj1** [comment]
@wallertech Ohh i know what your problem is i guess. press the c-key on the keyboard to go in fps camera or press the alt button to move with the standard maya-camera..

**Comment by wallertech** [comment]
rofl Im a bellend. Thanks @jannisj1.

**Comment by jannisj1** [comment]
@TheCherno i guess this can be closed now
